version: 2.1
jobs:
  build:
    working_directory: ~/content-player/player
    docker:
      - image: circleci/node:6.10-browsers
        environment:
           player_version_number: $CIRCLE_BRANCH
           build_number: $CIRCLE_BUILD_NUM
           filter_plugins: false
           
    steps:
      - checkout:
          path: ~/content-player
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      
      - run:
          name: clone plugins
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
            target_branch=$CIRCLE_BRANCH
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch
            else
            prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird-content-player/pulls/$CIRCLE_PR_NUMBER)
            target_branch=$(echo "${prdata}" | jq -r '.base.ref')
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch
            fi

      - run: sudo npm install -g grunt-cli@1.2.0
      - run: npm install
      - run: npm run build-preview sunbird
      - run: grunt compress:preview
      - run: grunt generate-libs
      - run: grunt build-jsdoc
    
      - run: 
          name: Install sonar scanner
          command: 'sudo npm install -g sonarqube-scanner'

      - run: 
          name: Sonar scanner
          command: |
            sonar-scanner -Dsonar.projectKey=project-sunbird_sunbird-content-player -Dsonar.organization=project-sunbird -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.language=js

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules

      - persist_to_workspace:
          root: ~/repo
          paths: .
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
