name: Code Quality Checks

on:
  push:
    branches:
      - '**'

jobs:
  code-quality:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '10.16.3'

    #   - name: Install grunt-cli
    #     run: sudo npm install -g grunt-cli@1.5.0

      - name: Configure git to use HTTPS
        run: git config --global url."https://".insteadOf git://

      - name: Restore node_modules cache
        id: cache
        uses: actions/cache@v4
        with:
          path: player/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Python 2
        run: |
          sudo apt-get update
          sudo apt-get install -y python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python
              
      - name: Set npm python config
        run: npm config set python /usr/bin/python2
              

    #   - name: Install pyenv
    #     run: |
    #       curl https://pyenv.run | bash
    #       export PATH="$HOME/.pyenv/bin:$PATH"
    #       eval "$(pyenv init --path)"
    #       eval "$(pyenv init -)"
    #       eval "$(pyenv virtualenv-init -)"
              
    #   - name: Install Python 2.7.18
    #     run: |
    #       export PATH="$HOME/.pyenv/bin:$PATH"
    #       eval "$(pyenv init --path)"
    #       eval "$(pyenv init -)"
    #       eval "$(pyenv virtualenv-init -)"
    #       pyenv install 2.7.18
    #       pyenv global 2.7.18
    #       python --version

    #   - name: Check Python version
    #     run: |
    #       source $HOME/.bashrc
    #       python --version

    #   - name: Install node-gyp
    #     run: npm install -g node-gyp

    #   - name: Set Python path in npm config
    #     run: npm config set python $(which python2)

      - name: Check Python version
        run: python --version
    
      - name: Install dependencies
        working-directory: player
        run: npm i --legacy-peer-deps
    
      - name: Save node_modules cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: player/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build preview
        run: npm run build-preview ekstep

      - name: Compress preview
        run: grunt compress:preview

      - name: Generate libs
        run: grunt generate-libs

      - name: Run test
        run: npm run test
